Change number of backtraces.
Note: i suspect that my development environment has been virused to add
illegal patch into MPlayerXP.

When i perform transition on to C++ then i found out the strange behaviour
of ld:
- [424] commit didn't break linkage of the project althrough this patch
  replaces some short C-names of functions with C++-long names. Therefore,
  short C-names like rtsp_session_start() were linked by g++ regardless the fact
  that official source-tree of project lost them.
- [437] commit emulates fixing of problem. I had movie which couldn't be played
  before this commit. But additional MSG_V() cannot fix anything in player.
  Furthermore, player after this commit doesn't print some symbols which it
  must print with this patch.
- list of suspect calls with -core.malloc-debug=3 option points me that some
  internal contexts of player were substituted by illegal patch. Additional
  proof of that is [434] commit. This commit did illegal patch thinner, but not
  removed it. Furthemore, each replace of #define with inline function or enum
  decreases size of project regardless on long C++-names of functions and data
  objects.

Well, one of goal transition project on C++ was using of C++ long-names which
are dynamically changed together with changing number or types of arguments.
But, it seems that there is big aliance against of me and my project. And i
suspect some objects from mplayerhq team who revenge me for fork using dirty
technology. Considering the fact that they hate C++ i'm suspecting that they
coerce somebody to attack my project and modify illegal patch parallel with
my improvements.

Additional observations:
- My local copy of g++ still prints: "warning: 'packed' attribute ignored"
  that makes win32loader non working at least. That warning became appears
  right after adding so-called small secury holes into structures of project.
- My local copy of /lib32/libgcc_s.so was damaged because demuxer returns -nan
  in pts field for each packet. Moreover, upgrade of gcc didn't help to solve
  this problem. Thus, i have no working 32-bit development environment.
- My 32-bit development environment (aka: gcc-4.5.4) printed:
--- 8< ----
In file included from ../osdep/cpudetect.h:4:0,
                 from win32.c:942:
../mplayerxp.h:130:20: error: invalid storage class for function 'escape_player'
../mplayerxp.h:130:20: warning: no previous prototype for 'escape_player'
../mplayerxp.h:135:23: error: invalid storage class for function 'check_pin'
../mplayerxp.h:135:23: warning: no previous prototype for 'check_pin'
--- 8< ---
mplayerxp.h:130:
static inline void escape_player(const char* why,unsigned num_calls) {
mplayerxp.h:135:
static inline MPXP_Rc check_pin(const char* module,unsigned pin1,unsigned pin2) {
--- 8< ---
- Last few days, 32-bit binary of mplayerxp is able to print help only and
  ignores command-line arguments.

But who is that (***insert any colorful phrases here***) analog of virus which
attacks my development environment and who is his host(s)?

Thus, i need find out the way to restore the quality of my development enviroment!


git-svn-id: https://svn.code.sf.net/p/mplayerxp/code@438 92b12bc1-bfd6-414e-abbc-3841631887cf